#FROM php:5.6-cli
FROM php:7-cli

RUN apt-get update && apt-get install -y \
        libxml2-dev
RUN	docker-php-ext-install soap
COPY ./test-soaplib.php /tmp/test-soaplib.php
WORKDIR /tmp
CMD [ "php", "./test-soaplib.php" ]
